### PR TITLE
accounts: load serial port from config file

### PR DESCRIPTION
**Pull request by fredericosilva**
This PR adds the serialPort on the accountManager config section.

Config example:
```ìni
# GCE Instance Configuration

[accountManager]
# disable=false
serialPort=COM2
```

### CODE REVIEW

**Comment by adjackura** [comment]
Add a test for the new function and update the package version in google-compute-engine-windows.goospec (should now be 4.2.3@1), and add an update to the releaseNotes section.

**Comment by adjackura** [comment]
Also do you have a specific use case where this is needed? Changing the default COM port would make the UI and gcloud not work as they expect output on port 4

**Comment by fredericosilva** [comment]
@adjackura I've added two test, can you have a look on that and let me know if that's want you were expecting?

I'm testing _GCEWindowsAgent_ on a HyperV environment there only two serial ports are available.

Thanks

**Comment by adjackura** [comment]
That seems like a very unique use case, the agent nor any of the guest software is designed or tested to run in any environment other than GCE, most if not all features will not work as expected. We also don't plan on adding support for other environments.  

Is there a specific reason you are running the agent in a HyperV environment that relates to your GCE workflow? If you want to use the agent in a stituation it was not designed for would forking the code make more sense for you?

**Comment by fredericosilva** [comment]
I was looking around, GCEWindowsAgent seems to be the best available solution to provide password reset on windows VMs. On HyperV there is this limitation of 2 serial ports. I was able to implement the password reset flow using a different serial port.

Instead of only forking I've decided to do this PR as it might be useful for other people playing around with the Agent on different environments.

I've a couple more settings that I would like to PR in order to fit on my environment, I understand that it will add more code to the project and it will make it harder to maintain.

If you see no value on those changes I'll go with forking and change those hardcoded values.

Thank you

**Comment by adjackura** [comment]
Sorry for the crazy late response, closing as this makes more sense in a fork.

**Pull request closed without merging**
